runtime: python311
entrypoint: gunicorn -k uvicorn.workers.UvicornWorker --bind :$PORT app.main:app

env: standard

automatic_scaling:
  max_instances: 20
  min_instances: 0
  max_idle_instances: 1
  min_idle_instances: 0
  target_cpu_utilization: 0.65

liveness_check:
  path: "/health"
  check_interval_sec: 30
  timeout_sec: 4
  failure_threshold: 2
  success_threshold: 2

handlers:
  - url: /.*
    script: auto

inbound_services:
  - warmup
